\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename ratpoison.info
@settitle ratpoison manual
@setchapternewpage odd
@c %**end of header

@ifinfo
@format
START-INFO-DIR-ENTRY
* ratpoison: (ratpoison).                     A rat-free Window Manager.
END-INFO-DIR-ENTRY
@end format

@ifinfo
This is the ratpoison user manual.

Copyright @copyright{} 2000 Shawn Betts

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.

@ignore
Permission is granted to process this file through TeX
and print the results, provided the printed document
carries a copying permission notice identical to this
one except for the removal of this paragraph (this
paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified
versions of this manual under the conditions for
verbatim copying, provided also that the sections
entitled ``Copying'' and ``GNU General Public License''
are included exactly as in the original, and provided
that the entire resulting derived work is distributed
under the terms of a permission notice identical to this
one.

Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation approved by the Free Software Foundation.
@end ifinfo

@titlepage
@sp 10
@titlefont{Ratpoison}
@author Shawn Betts

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2000 Shawn Betts

Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.

Permission is granted to copy and distribute modified
versions of this manual under the conditions for
verbatim copying, provided also that the sections
entitled ``Copying'' and ``GNU General Public License''
are included exactly as in the original, and provided
that the entire resulting derived work is distributed
under the terms of a permission notice identical to this
one.

Permission is granted to copy and distribute
translations of this manual into another language,
under the above conditions for modified versions,
except that this permission notice may be stated in a
translation approved by the Free Software Foundation.
@end titlepage
     
@end ifinfo

@ifinfo
This document explains how to use ratpoison.
@end ifinfo

@node Top, About, (dir), (dir)

@menu
* About::                       What is ratpoison?
* Contacting::                  How do I contact the ratpoison developers?
* Using ratpoison::             Key commands and functionality
@end menu

@node About, Contacting, Top, Top
@chapter About

ratpoison is a simple Window Manager with no fat library dependencies,
no fancy graphics, no window decorations, and no flashy wank. It is
largely modelled after GNU Screen which has done wonders in virtual
terminal market.

All interaction with the window manager is done through
keystrokes. ratpoison has a prefix map to minimize the key clobbering
that cripples EMACS and other quality pieces of software.

You'll also be pleased to hear that there is NO ratpoison.conf to
configure. If you want to configure ratpoison, edit the source.

ratpoison was written by Shawn Betts (@email{sabetts@@users.sourceforge.net}).

@node Contacting, Using ratpoison, About, Top
@chapter Contacting
ratpoison is hosted on @url{sourceforge.net}. To see the latest
developments in ratpoison go to
@url{http://www.sourceforge.net/projects/ratpoison} or visit the
ratpoison webpage at @url{http://ratpoison.sourceforge.net}.

There is also a ratpoison mailing list:
@email{ratpoison-devel@@lists.sourceforge.net}. For details on subscribing
and for the list archives go to the ratpoison sourceforge.net project.

@node Using ratpoison,  , Contacting, Top
@chapter Using ratpoison

ratpoison is a very simple window manager. Each window is maximized and
has no border decorations. Here is a list of commands and what they do:

@table @kbd

@item C-t C-c
This opens a new XTerm.

@item C-t C-e
This opens a new EMACS session. You will probably only need to do this
once.

@item C-t C-w
This displays the Program Bar which displays the windows you currently
have running. The number before each window name is used to jump to that
window. You can to this by typing @kbd{C-t C-<n>} where @kbd{<n>} is the
number of the window. Note that only windows with numbers from 0 to 9
can be referenced.

After 5 seconds the Program Bar disappears.

@item C-t C-p
This jumps you to the previous window in the window list.

@item C-t C-n
This jumps you to the next window in the window list.

@item C-t C-<n>
This jumps you to window <n> where <n> is the window number as shown in
the Program Bar.

@item C-t C-t
This toggles between the current window and the last window.

@item C-t t
Sometimes you need to send a C-t to the current window. This keystroke
does just that.

@item C-t k
This deletes the current window.

@item C-t K
This destroys the current window. Normally you should only need to use
@kbd{C-t k}, but just incase you need to rip the heart out of a
misbehaving window this command should do the trick.

@end table

@bye

