#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/ratpoison

# Written by Jim Van Zandt <jrv@vanzandt.mv.com>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.
# modified for ratpoison by Bernhard R. Link <brlink@debian.org>

FLAVOR="$1"
PACKAGE=ratpoison
ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}
FILES=ratpoison-cmd.el

if [ ${FLAVOR} = emacs ]; then
	exit 0
fi
for file in ${FILES} ; do
	if [ ! -f ${ELDIR}/${file} ]; then 
		echo "Warning: missing file ${ELDIR}/${file}!" >&2
		exit 0
	fi
done

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

FLAVORTEST=`echo $FLAVOR | cut -c-6`
if [ ${FLAVORTEST} = xemacs ] ; then
    SITEFLAG="-no-site-file"
else
    SITEFLAG="--no-site-file"
fi
FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
cp ${FILES} ${ELCDIR}
cd ${ELCDIR}

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
${FLAVOR} ${FLAGS} ${FILES}
rm -f *.el path.el

exit 0
