#! /bin/sh
# prerm script for ratpoison

set -e

case "$1" in
    remove|deconfigure)
    	update-alternatives --remove x-window-manager /usr/bin/ratpoison
	if [ -d /var/lib/ratpoison/menu ] ; then
		rm /var/lib/ratpoison/menu/*.menu || true
	fi
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# taken from dh_pysupport:
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c -i /usr/share/python-support/ratpoison
fi

#DEBHELPER#

exit 0
