name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get install -y libx11-dev libxft-dev libxrandr-dev libxtst-dev libxres-dev
    - name: install clang-tools for make regress
      run: sudo apt-get install -y clang-tools
    - name: make
      run: make
    - name: scan-build
      run: make regress
    - name: test install with DESTDIR
      run: sudo make install DESTDIR=/usr/gooses; size /usr/gooses/usr/local/bin/sdorfehs
